post http://127.0.0.1:3200/users
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ4NzQ2NCwiZXhwIjoxNjMyNDk0NjY0fQ.8xgVj7b7_MqkM2OG62OVn5eKhBuqhO9O2vqmx6ixqAI

{
    "username": "keyra",
    "password": "keyra1818",
    "nama": "Keyra Almira",
    "email": "keyra@gmail.com",
    "level": "operator"
}

###
delete http://127.0.0.1:3200/users/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpemFsIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ2MTgyMiwiZXhwIjoxNjMyNDY5MDIyfQ.hkd5wa7MXiiwo8JHZ1gHwLEOHBB9p3CPhyXZQ0eLLwk

{
    "email": "rizal.safril@gmail.com",
    "password": "safrils",
    "nama": "Safrizal"
}


###
get http://127.0.0.1:3200/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ5NjgwMCwiZXhwIjoxNjMyNTA0MDAwfQ.TIFPy-nDAUOtjyxxAuLwOmIDDMsGsjHYbJ6YNH9kyks

{
    "product_name": "Mie Udang",
    "product_type": "Makanan",
    "price": 16000,
    "stock": 85,
    "notes": "Yang maknyus"
}

###
get http://127.0.0.1:3200/categories
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ5NDkxNSwiZXhwIjoxNjMyNTAyMTE1fQ.6d447UAyKIKoc8hBQ6LEh7q-aVx9V53fPheiCOewpZo

{
    "product_id": 2,
    "categ_name": "gojek",
    "service_fee": 20000
}

###
get http://127.0.0.1:3200/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ5NjgwMCwiZXhwIjoxNjMyNTA0MDAwfQ.TIFPy-nDAUOtjyxxAuLwOmIDDMsGsjHYbJ6YNH9kyks

{
    "cust_name": "Ridwan",
    "notes": "Take away"
}


###
get http://127.0.0.1:3200/billings
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ5NDkxNSwiZXhwIjoxNjMyNTAyMTE1fQ.6d447UAyKIKoc8hBQ6LEh7q-aVx9V53fPheiCOewpZo

{
    "user_id": 1,
    "cust_id": 2,
    "category_id": 2
}


###
get http://127.0.0.1:3200/history
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjUwMjI0NSwiZXhwIjoxNjMyNTA5NDQ1fQ.PGllXlyLaLMbC8nXh1a_T1ag5tsgQDUSC_8C3zbvHm8

{
    "user_id": 1,
    "cust_id": 1,
    "category_id": 2
}


# {
#   "fieldCount": 0,
#   "affectedRows": 1,
#   "insertId": 1,
#   "serverStatus": 2,
#   "warningCount": 0,
#   "message": "",
#   "protocol41": true,
#   "changedRows": 0
# }