put http://127.0.0.1:3200/users/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ4NzQ2NCwiZXhwIjoxNjMyNDk0NjY0fQ.8xgVj7b7_MqkM2OG62OVn5eKhBuqhO9O2vqmx6ixqAI

{
    "username": "keyra",
    "password": "keyra1818",
    "nama": "Keyra Almira",
    "email": "keyra@gmail.com",
    "level": "operator"
}

###
delete http://127.0.0.1:3200/users/3
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpemFsIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ2MTgyMiwiZXhwIjoxNjMyNDY5MDIyfQ.hkd5wa7MXiiwo8JHZ1gHwLEOHBB9p3CPhyXZQ0eLLwk

{
    "email": "rizal.safril@gmail.com",
    "password": "safrils",
    "nama": "Safrizal"
}


###
get http://127.0.0.1:3200/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ4NzQ2NCwiZXhwIjoxNjMyNDk0NjY0fQ.8xgVj7b7_MqkM2OG62OVn5eKhBuqhO9O2vqmx6ixqAI

{
    "product_name": "Teh Dingin",
    "product_type": "Minuman",
    "price": 7000,
    "stock": 100,
    "notes": "Yang dingin"
}

###
get http://127.0.0.1:3200/categories
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ4NzQ2NCwiZXhwIjoxNjMyNDk0NjY0fQ.8xgVj7b7_MqkM2OG62OVn5eKhBuqhO9O2vqmx6ixqAI

{
    "product_id": 2,
    "categ_name": "grab",
    "service_fee": 21000
}

###
get http://127.0.0.1:3200/customer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ4NzQ2NCwiZXhwIjoxNjMyNDk0NjY0fQ.8xgVj7b7_MqkM2OG62OVn5eKhBuqhO9O2vqmx6ixqAI

{
    "cust_name": "Reza",
    "notes": "Take away"
}


###
post http://127.0.0.1:3200/billings
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtleXJhIiwibGV2ZWwiOiJvcGVyYXRvciIsImlhdCI6MTYzMjQ3OTk5OSwiZXhwIjoxNjMyNDg3MTk5fQ.m3IfOgGcgmEmyJOQ8GfmdWoNHFQVjhGflEEImGcBpAI

{
    "user_id": 1,
    "cust_id": 3,
    "category_id": 2
}


# {
#   "fieldCount": 0,
#   "affectedRows": 1,
#   "insertId": 1,
#   "serverStatus": 2,
#   "warningCount": 0,
#   "message": "",
#   "protocol41": true,
#   "changedRows": 0
# }